# Generated by Django 3.0 on 2022-03-19 17:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media_files/Categories/icon')),
                ('icon_class', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('lead_img', models.ImageField(blank=True, null=True, upload_to='media_files/blog')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('summary', models.TextField(blank=True, help_text='31 letters max will give a better out look', null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='media_files/authorImg')),
                ('youtube_video_link', models.TextField(blank=True, null=True)),
                ('num_views', models.CharField(blank=True, max_length=30, null=True)),
                ('read_time', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.ManyToManyField(blank=True, to='blog.Categories')),
            ],
        ),
    ]
