# Generated by Django 3.0 on 2022-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220320_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, default='wmecreatives', max_length=200, null=True),
        ),
    ]
