# Generated by Django 3.0 on 2022-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220320_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
