# Generated by Django 3.0 on 2022-03-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articles_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='article image', max_length=300, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name',
        ),
    ]
