# Generated by Django 3.0 on 2022-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='google code', max_length=200, null=True)),
                ('code_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
