# Generated by Django 3.2.10 on 2022-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos_collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uploded', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('photographer', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='api_photos')),
            ],
        ),
    ]
