# Generated by Django 3.2.10 on 2022-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_photos_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_status',
            field=models.CharField(blank=True, choices=[('publish', 'publish'), ('draft', 'draft')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photos_collections',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos_collections',
            name='name',
            field=models.CharField(blank=True, default='api image', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photos_collections',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='api_photos'),
        ),
    ]
