# Generated by Django 3.2.10 on 2022-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220402_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='draft',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
