# Generated by Django 3.2.10 on 2022-06-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articles_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='draft',
        ),
    ]
