# Generated by Django 3.0 on 2023-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_articles_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='lead_img_alt',
            field=models.TextField(blank=True, help_text='alt text of an image', null=True),
        ),
    ]
