# Generated by Django 3.0 on 2023-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_articles_lead_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='lead_img_alt',
            field=models.CharField(blank=True, help_text='alt text of an image', max_length=1000, null=True),
        ),
    ]
